### ISSUE TITLE
Improve API error feedback

### ISSUE THREAD

**Issue by maxyzli** [ic3network/mccs-alpha-api#10]

**Comment by geoffturk** [comment]
https://developer.twitter.com/en/docs/basics/response-codes
See the "error codes" section.
```
{
  "errors": [
    {
      "message": "Last name field is mandatory.",
      "code": 64
    }
  ]
}
```

Another option could be:
```
{
{
  "errors": [
    {
      "source": "lastName",
      "type": "MISSING_MANDATORY_PROPERTY",
      "message": "Last name field is mandatory."
    },
    {
      "source": "dailyEmailMatchNotification",
      "type": "INVALID_FORMAT",
      "message": "Email notification field must be a boolean value of either true or false."
    },
    {
      "source": "telephone",
      "type": "INVALID_FORMAT",
      "message": "Telephone field can only contain numbers, spaces and an optional + sign"
    }
  ]
}
```

I like working with a `source`/`type` combination rather than having to create and maintain a list of error codes. 

It also facilitates testing so that tests check the correct `source` and `type` are returned, but message wording can be changed without breaking the tests.

**Comment by maxyzli** [comment]
Also better error message for the JSON decode error

```go
{
    "errors": [
        {
            "message": "json: cannot unmarshal string into Go struct field SignupRequest.showRecentMatchedTags of type bool"
        }
    ]
}
```

**Comment by geoffturk** [comment]
Also:

![image](https://user-images.githubusercontent.com/32190662/77516659-11fc4680-6e7b-11ea-8888-d7de6e5e8c2b.png)

And from PostgreSQL:

![image](https://user-images.githubusercontent.com/32190662/77516695-20e2f900-6e7b-11ea-864c-0001edd9d2d8.png)
