### ISSUE TITLE
Create an entity during user signup

### ISSUE THREAD

**Issue by maxyzli** [ic3network/mccs-alpha-api#12]

**Comment by geoffturk** [comment]
Maybe add an array of `_id`s in the user object that links to the entity, and vice versa in the entity object linking to user `_id`s. There will only be one `_id` in each array to start.

**Comment by maxyzli** [comment]
If we want to do the many to many relationships, we should think about it right now. Other we will change a lot of the logic (transaction part).

**Comment by maxyzli** [comment]
We need to think about how the logic work in the many to many relationships even we only have one id in the array. Because the data structure has complete change (from a single field `entityID` to an array of `_ids`). 

I don't think it is reasonable to have both a single field (`entityID`) and an array of `_ids` co-exist in the database and we only use one of them.

**Comment by geoffturk** [comment]
> I don't think it is reasonable to have both a single field (entityID) and an array of _ids co-exist in the database and we only use one of them.

I agree. We either make the change now and rewrite the code in all of the places where the entityID  is accessed, or we save it for later.

I suggest we go for the first option since we can just change it as we refactor the old code into the API code. 

And it will force us to think about multi-user access to transactions sooner rather than later, which is a good thing.
